name: Prettier
run-name: Running prettier
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          gh api --method POST 
           -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$OWNER/$REPO/actions/runs/$RUN_ID/approve
        env:
          RUN_ID: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner }}
          REPO: ${{ github.event.repository.name }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,md,js,tsx}
          commit_message: 'ci: prettified code'
