name: Prettier
run-name: Running prettier
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: git init .
      - run: git config user.name github-actions 
      - run: git config user.email github-actions@github.com
      - run: git remote add origin ${{ github.event.pull_request.head.repo.clone_url }}
      - run: git fetch origin
      - run: git switch ${{ github.event.pull_request.head.ref }}

      # GitHub CLI api
      # https://cli.github.com/manual/gh_api
      - run: |
          gh api --method POST \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/${{ github.event.pull_request.head.repo.owner.name }}/${{ github.event.pull_request.head.repo.name }}/actions/runs/${{ github.run_id }}/approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     # Make sure the actual branch is checked out when running on pull requests
      #     ref: ${{ github.event.pull_request.head.ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,md,js,tsx}
          commit_message: 'ci: prettified code'
