name: Prettier
run-name: Running prettier
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: git config user.name github-actions 
      - run: git config user.email github-actions@github.com
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,md,js,tsx}
          commit_message: 'ci: prettified code'
